---
title: "Introduction to R"
author: "Hazim Fitri"
date: "2024-12-18"
output: pdf_document
---

# Introduction to R

## Indexing techniques

### Sample Vector

`{r} v = c(1,4,4,3,2,2,3) v}`

Number indexing: it'll take the value from the number that we've specify. R start its index from 1 instead of 0 like Python. Below code will extract the third value from the left.

`{r} v[3]}`

We can also extract multiple value from a vector by using another vector. The order of the output will depend on the order of the index. Thus, you can rearrange the order of your output using indexing. For example, code below will extract the value from column 2, 4, and 5

`{r} v[c(2,6,5)]}`

### Sample Data Frame

The same can also be applied to data frame. For <example:->

`{r} data = read.table(header=T, text='                   subject sex size                   1 M 7                   2 F 6                   3 F 9                   4 M 11') data}`

`{r} data[c(2,3),c(3,1)]}`

For data with named column or row, we can index by using name. For <example:->

`{r} data[c('size', 'sex')]}`

## Indexing through Boolean

This type of indexing will return all output with 'TRUE' value. For <example:->

`{r} v[v>2]}`

`{r} data$sex == 'M' &  data$size > 6}`

```{r}

```
